spring.application.name=pauta-votacao-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pauta_votacao}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

logging.level.root=INFO
logging.level.com.ialedocarmo.pauta_votacao_api=INFO

app.urls.callback-base-url=${APP_CALLBACK_BASE_URL:http://localhost:8080}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-produces-media-type=application/json

